/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Category_children: typeof import('./src/components/Category_children.vue')['default']
    Category_commodity: typeof import('./src/components/Category_commodity.vue')['default']
    Category_computer: typeof import('./src/components/Category_computer.vue')['default']
    Category_feature: typeof import('./src/components/Category_feature.vue')['default']
    Category_homeAppliances: typeof import('./src/components/Category_homeAppliances.vue')['default']
    Category_homeApplience: typeof import('./src/components/Category_homeApplience.vue')['default']
    Category_parts: typeof import('./src/components/Category_parts.vue')['default']
    Category_radio: typeof import('./src/components/Category_radio.vue')['default']
    Category_recommend: typeof import('./src/components/Category_recommend.vue')['default']
    Category_redmi: typeof import('./src/components/Category_redmi.vue')['default']
    Category_service: typeof import('./src/components/Category_service.vue')['default']
    Category_smallHomeAppliances: typeof import('./src/components/Category_smallHomeAppliances.vue')['default']
    Category_smart: typeof import('./src/components/Category_smart.vue')['default']
    Category_smartHome: typeof import('./src/components/Category_smartHome.vue')['default']
    Category_travel: typeof import('./src/components/Category_travel.vue')['default']
    Category_xiaomi: typeof import('./src/components/Category_xiaomi.vue')['default']
    NavComponents: typeof import('./src/components/bottom-navBar/navComponents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanAddressEdit: typeof import('vant/es')['AddressEdit']
    VanAddressList: typeof import('vant/es')['AddressList']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
